[package]
name = "craby_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Craby core"
license = "MIT"
repository = "https://github.com/leegeunhyeok/craby"

[dependencies]
cxx = { workspace = true }
